### ISSUE TITLE
What Client Id + Secret?

### ISSUE THREAD

**Issue by LookslikeLenni** [alecchendev/spotify-refresh-token#1]
help im lost

Edit:
ok i actually found them but now it says:

INVALID_CLIENT: Invalid redirect URI

**Comment by alecchendev** [comment]
Inside your spotify developer dashboard for your app see "edit settings" and add "https://getyourspotifyrefreshtoken.herokuapp.com/callback" to your Redirect URIs there. Hopefully that helps!
