### ISSUE TITLE
Refresh token is invalid

### ISSUE THREAD

**Issue by robotzurg** [alecchendev/spotify-refresh-token#5]
I've tried using this to get my spotify refresh token, but my project says the refresh token is invalid. I'm doing it all the correct way...?

**Comment by alecchendev** [comment]
Could you provide your code and error message? Just from this I'm not sure what it might be.

**Comment by robotzurg** [comment]
I'm given a refresh token and an access token, neither of which seem to work. The error message is this:

WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API.
Details: invalid_grant Invalid refresh token.

I know for a fact my code does not work because I have a refresh token (actually from the previous iteration of your website) that did work and continues to work for me. I found another solution to get a refresh token, but it would be nice to figure out why this one didn't work specifically?

**Comment by alecchendev** [comment]
Honestly I'm not super sure what it might be, and I haven't revisited this project in quite a while. The user is able to revoke the refresh token so maybe that's a possibility, or maybe the refresh token expired? Glad you figured out another way however.
